# Generated by Django 3.0.4 on 2020-04-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=64)),
                ('size', models.CharField(choices=[('S', 'small'), ('L', 'large')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='price in £', max_digits=4)),
                ('extras', models.ManyToManyField(blank=True, to='orders.SubExtra')),
            ],
        ),
    ]
