# Generated by Django 3.0.4 on 2020-04-17 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_sub'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sub',
            new_name='Sub_new',
        ),
    ]
