# Generated by Django 3.0.4 on 2020-04-17 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200417_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub',
            old_name='sub',
            new_name='name',
        ),
    ]
