# Generated by Django 3.0.4 on 2020-04-17 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200417_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub',
            old_name='name',
            new_name='sub',
        ),
    ]
