# Generated by Django 3.0.4 on 2020-04-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200417_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='large',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='small',
        ),
        migrations.AddField(
            model_name='sub',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='sub',
            name='sub_size',
            field=models.CharField(choices=[('S', 'S'), ('L', 'L')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='sub',
            name='sub',
            field=models.CharField(default='sub_name', max_length=20),
        ),
    ]
