# Generated by Django 3.0.4 on 2020-04-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200418_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_size', models.CharField(choices=[('S', 'S'), ('L', 'L')], default='S', max_length=2)),
                ('pizza_style', models.CharField(choices=[('regular', 'Regular'), ('sicilian', 'Sicilian')], default='Regular_pizza', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=8.7, max_digits=4)),
                ('topping', models.ManyToManyField(to='orders.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='Toppinprice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='regularpizza',
            name='topping',
        ),
        migrations.DeleteModel(
            name='SicilianPizza',
        ),
        migrations.DeleteModel(
            name='RegularPizza',
        ),
        migrations.AddField(
            model_name='topping',
            name='price',
            field=models.ManyToManyField(to='orders.Toppinprice'),
        ),
    ]
