# Generated by Django 3.0.4 on 2020-04-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200424_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='price',
        ),
        migrations.AddField(
            model_name='topping',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=4),
        ),
    ]
