# Generated by Django 3.0.4 on 2020-04-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200424_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_style',
            field=models.CharField(choices=[('Regular_pizza', 'Regular_pizza'), ('Sicilian_pizza', 'Sicilian_pizza')], default='Regular_pizza', max_length=20),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='topping',
            field=models.ManyToManyField(related_name='pizzas', to='orders.Topping'),
        ),
    ]
