# Generated by Django 3.0.4 on 2020-04-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200424_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='pizza_size',
            field=models.CharField(choices=[('small', 'S'), ('large', 'L')], default='small', max_length=10),
        ),
        migrations.AlterField(
            model_name='sub',
            name='sub_size',
            field=models.CharField(choices=[('small', 'small'), ('large', 'large')], default='small', max_length=10),
        ),
    ]
