# Generated by Django 3.0.4 on 2020-04-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200424_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerplatter',
            name='dinner_size',
            field=models.CharField(choices=[('small', 'small'), ('large', 'large')], default='small', max_length=10),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_style',
            field=models.CharField(choices=[('Regular pizza', 'Regular pizza'), ('Sicilian pizza', 'Sicilian pizza')], default='Regular_pizza', max_length=20),
        ),
    ]
