# Generated by Django 3.0.4 on 2020-04-25 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200425_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='large',
        ),
        migrations.RemoveField(
            model_name='dinnerplatter',
            name='small',
        ),
    ]
