# Generated by Django 3.0.4 on 2020-05-09 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200425_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('stock', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('size', models.CharField(choices=[('small', 'small'), ('large', 'large')], max_length=10, null=True)),
                ('pizza_style', models.CharField(choices=[('Regular pizza', 'Regular pizza'), ('Sicilian pizza', 'Sicilian pizza')], max_length=20, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Category')),
                ('topping', models.ManyToManyField(blank=True, to='orders.Topping')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('name',),
            },
        ),
        migrations.DeleteModel(
            name='DinnerPlatter',
        ),
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping',
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='pizza_ptr',
        ),
        migrations.DeleteModel(
            name='Salad',
        ),
        migrations.DeleteModel(
            name='Sub',
        ),
        migrations.DeleteModel(
            name='Toppinprice',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='PizzaOrder',
        ),
    ]
